version: '3'
services:

  db:
    image: eclipse/rdf4j-workbench:amd64-latest
    ports:
    - "8080:8080"

  server:
    build: .
    ports:
    - "80:5000"
    depends_on:
    - db
    links: 
    - "db:database"

